---
language: python
python: "2.7"

# Use the new container infrastructure
name: Ubuntu
sudo: required

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # role check
  #- ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo

  # make sure it's idempotent
  #- >
  #ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
  #| grep -q 'changed=0.*failed=0'
  #&& (echo 'Idempotence test: pass' && exit 0)
  #|| (echo 'Idempotence test: fail' && exit 1)


notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
